### ISSUE TITLE
Методы работы с видео

### ISSUE THREAD

**Issue by NikitaShulgan** [intsystems/CreationOfIntelligentSystems_video_fMRI#2]

**Comment by pollinab** [comment]
[VideoMethods.pdf](https://github.com/intsystems/CreationOfIntelligentSystems_video_fMRI/files/9701394/VideoMethods.pdf)

**Comment by pollinab** [comment]
[VideoMethods.pdf](https://github.com/intsystems/CreationOfIntelligentSystems_video_fMRI/files/9701396/VideoMethods.pdf.pdf)
